import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { convertNumberToBinary, createDoors, randomNumber } from "../helpers";
import { Card } from "../components/Card";
import { NumberInput } from "../components/NumberInput";
import Link from "next/link";

const Home: NextPage = () => {
  const [doorQty, setDoorQty] = useState(3);
  const [withGift, setWithGift] = useState("start");

  useEffect(() => {
    const newNumber = randomNumber(doorQty);

    setWithGift(convertNumberToBinary(newNumber));
  }, [doorQty]);

  return (
    <div>
      <Head>
        <title>Monty Hall</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.form}>
        <div>
          <Card backgroundColor='#c0392c'>
            <h1>Monty Hall</h1>
          </Card>
          <Card>
            <NumberInput
              text='door guantity'
              value={doorQty}
              onChange={(newValue) => setDoorQty(newValue)}
            />
          </Card>
        </div>
        <div>
          <Card>
            <h1>Door with Gift</h1>
          </Card>
          <Card backgroundColor='#28a085'>
            <Link href={`game/${doorQty}/${withGift}`} passHref>
              <h2 className={styles.link}>Start</h2>
            </Link>
          </Card>
        </div>
      </main>
    </div>
  );
};

export default Home;
