import type { NextPage } from "next";
import Head from "next/head";
import { Door } from "../components/Door";
import { Gift } from "../components/Gift";
import styles from "../styles/Home.module.css";
import DoorModel from "../model/door";
import { useState } from "react";
import { createDoors } from "../functions/doors";

const Home: NextPage = () => {
  const [doors, setDoors] = useState(createDoors(3, 2));

  const renderingDoors = () =>
    doors.map((door, index) => (
      <Door value={doors} key={door.number} onChange={console.log} />
    ));
  return (
    <div className={styles.container}>
      <Head>
        <title>Monty Hall</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {renderingDoors()}
      <Gift />
    </div>
  );
};

export default Home;
