import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Door } from "../components/Door";
import { Gift } from "../components/Gift";
import styles from "../styles/Home.module.css";
import DoorModel from "../model/door";

const Home: NextPage = () => {
  const p1 = new DoorModel(1);
  const p2 = new DoorModel(2);
  return (
    <div className={styles.container}>
      <Head>
        <title>Monty Hall</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Gift />
      <Door door={p1} />
      <Door door={p2} />
    </div>
  );
};

export default Home;
